--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fuyutsuki/Texter
branches:
  - master
  - legacy/php7.0.x
projects:
  Texter:
    path: ""
    icon: "/assets/Logo.png"
    libs:
      - src: fuyutsuki/libform/libform
        version: 0.1.1
...
