--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fuyutsuki/Texter
branches:
  - master
projects:
  Texter:
    path: ""
    icon: "/assets/Logo.png"
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: 2.1.0
...
