name: Texter
main: tokyo\pmmp\Texter\Core
version: 3.0.0
api:
# pmmp/PocketMine-MP
  - 3.0.0
author: yuko_fuyutsuki
authors:
# SpecialThanks(敬称略)
- mfmfnek0
- onebone
- ogiwara
- Shootsta_ERU0531
- Toganon
- ShadowArt
- Marron0421
website: https://github.com/fuyutsuki/Texter

permissions:
 texter.*:
  default: op
  description: permission that allows player to use texter
  children:
   texter.command.*:
    default: op
    description: permission that allows player to use texter
    children:
      texter.command.txt:
        default: true # もしopのみ実行させたい場合は op と記述してください
        description: permission that allows player to use /txt
      texter.command.txtadm:
        default: op
        description: permission that allows player to use /txtadm
